### ISSUE TITLE
Skip uploading too large files to Wikimedia Commons

### ISSUE THREAD

**Issue by macbre** [wikimedia-pl/mbc-importer#55]
```
2024-12-25 19:47:29 upload_to_commons                   INFO     Fetching <https://mbc.cyfrowemazowsze.pl/Content/58369/Galeria/00063254-0001.tif> into mbc-harvest-18h31gsg temporary file
2024-12-25 19:47:32 upload_to_commons                   INFO     HTTP 200 (22.27 MB)
ERROR: An error occurred for uri https://commons.wikimedia.org/w/api.php
ERROR: Traceback (most recent call last):
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/pywikibot/data/api/_requests.py", line 682, in _http_request
    response = http.request(self.site, uri=uri,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/pywikibot/comms/http.py", line 280, in request
    r = fetch(baseuri, headers=headers, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/pywikibot/comms/http.py", line 452, in fetch
    callback(response)
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/pywikibot/comms/http.py", line 338, in error_handling_callback
    raise response from None
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/pywikibot/comms/http.py", line 443, in fetch
    response = session.request(method, uri,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbre/git/mbc-importer/env/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError('The write operation timed out'))

WARNING: Waiting 5.0 seconds before retrying.
```

**Comment by macbre** [comment]
https://doc.wikimedia.org/pywikibot/stable/api_ref/pywikibot.config.html#settings-to-avoid-server-overload
